# Generated by Django 5.1.6 on 2025-02-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("O", "female"), ("1", "male")], max_length=1
                    ),
                ),
                ("age", models.PositiveSmallIntegerField()),
                ("favorite_number", models.PositiveSmallIntegerField()),
                ("created", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
